### ISSUE TITLE
bot token and prefix

### ISSUE THREAD

**Issue by darkiceop** [Salazar34/Mod-BOT#1]
where is bot token and perfix man i cant see in code

**Comment by Salazar34** [comment]
@darkiceop you have to create a bot yourself. In order to do this: 
1. Go to the following link (https://discord.com/developers/applications)
2. Login with your discord account.
3. At the top right, you can see a button "New Application"; Press it and create a new application.
4. Then, at the left in the menu, click on "Bot" and make your application a bot.
5. After that, you can see under the image and the name a sentence with says "Click here to reveal token". I remember you that the token of your bot is personal information. You don't have to share it on the web. Take it a secret.
6. After that, you can work on your own bot.

For the prefix, you can find it here https://github.com/Salazar34/Mod-BOT/blob/main/bot.py at line 27. If you want to change the prefix, you're free to do this.
